name: Check Format
on: [workflow_dispatch, pull_request]

jobs:
  check_format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: format code
        run: ./format.sh

      - name: check diff
        run: git diff --color=always --exit-code
